import { ESPECIALIDADES_BASE } from './catalogo';
import { slugify } from './texto';
import type {
  BaseListaMedica,
  Ciudad,
  Consultorio,
  Faq,
  Genero,
  ProfEspecialidad,
  Profesional,
  Servicio,
} from './tipos';

/**
 * Doce perfiles ficticios con datos verosímiles de Puebla, Cholula y Atlixco.
 *
 * Van marcados con estatus 'demo' justamente para poder borrarlos de un tirón
 * cuando entren los primeros profesionales reales:
 *   DELETE FROM profesionales WHERE estatus = 'demo';
 * Ningún dato de aquí corresponde a una persona real.
 */

interface Semilla {
  nombre: string;
  apellidos: string;
  titulo: string;
  genero: Genero;
  cedula: string;
  cedula_especialidad: string;
  especialidades: string[];
  bio: string;
  telefono: string;
  whatsapp: string;
  idiomas: string[];
  anios: number;
  universidad: string;
  universidad_especialidad: string;
  consejo: string;
  vigencia: string;
  aseguradoras: string[];
  rating: number | null;
  resenas: number | null;
  verificado: string | null;
  fundador: boolean;
  consultorio: {
    calle: string;
    numero: string;
    torre: string;
    piso: string;
    consultorio: string;
    colonia: string;
    cp: string;
    ciudad: Ciudad;
    lat: number;
    lng: number;
    referencias: string;
    estacionamiento: string;
    horario: string;
    finSemana: boolean;
  };
  servicios: [string, number | null, boolean][];
  faqs: [string, string][];
}

const SEMILLAS: Semilla[] = [
  {
    nombre: 'Mariana',
    apellidos: 'Salgado Ocampo',
    titulo: 'Dra.',
    genero: 'femenino',
    cedula: '7418206',
    cedula_especialidad: '10934472',
    especialidades: ['esp-dermatologia'],
    bio: 'Dermatóloga con consulta en Angelópolis. Atiende padecimientos de piel en adultos y adolescentes, con énfasis en acné, dermatitis y revisión de lunares. Trabaja con dermatoscopía digital y da seguimiento fotográfico de cada lesión.',
    telefono: '2223104477',
    whatsapp: '2223104477',
    idiomas: ['Español', 'Inglés'],
    anios: 12,
    universidad: 'Benemérita Universidad Autónoma de Puebla',
    universidad_especialidad: 'Universidad Nacional Autónoma de México',
    consejo: 'Consejo Mexicano de Dermatología',
    vigencia: '2028',
    aseguradoras: ['GNP', 'AXA', 'Metlife'],
    rating: 4.8,
    resenas: 137,
    verificado: '2026-02-11',
    fundador: true,
    consultorio: {
      calle: 'Boulevard del Niño Poblano',
      numero: '2901',
      torre: 'Torre Médica II',
      piso: '5',
      consultorio: '507',
      colonia: 'Angelópolis',
      cp: '72197',
      ciudad: 'puebla',
      lat: 19.0173,
      lng: -98.24,
      referencias: 'Frente a la entrada norte del centro comercial; el acceso a torres médicas es por el estacionamiento techado.',
      estacionamiento: 'Estacionamiento del complejo, primera hora sin costo con validación en recepción.',
      horario: 'Lunes a viernes de 10:00 a 19:00. Sábados de 10:00 a 14:00.',
      finSemana: true,
    },
    servicios: [
      ['Consulta dermatológica', 900, true],
      ['Revisión de lunares con dermatoscopía', 1200, true],
      ['Criocirugía de lesiones benignas', 1500, true],
      ['Biopsia de piel', null, false],
    ],
    faqs: [
      ['¿Necesito llevar estudios previos?', 'Si ya te hicieron biopsias o estudios de laboratorio relacionados con la piel, llévalos. Si no tienes ninguno, no hace falta: la primera consulta incluye la revisión completa.'],
      ['¿Atiende niños?', 'A partir de los 12 años. Para menores de esa edad conviene una consulta con dermatología pediátrica y con gusto te oriento a dónde acudir.'],
    ],
  },
  {
    nombre: 'Ricardo',
    apellidos: 'Terrazas Villaseñor',
    titulo: 'Dr.',
    genero: 'masculino',
    cedula: '5892134',
    cedula_especialidad: '9217634',
    especialidades: ['esp-cardiologia', 'esp-medicina-interna'],
    bio: 'Cardiólogo e internista. Lleva control de hipertensión, arritmias e insuficiencia cardiaca, y realiza electrocardiograma y ecocardiograma en el propio consultorio para no mandar al paciente a otro lado.',
    telefono: '2222455189',
    whatsapp: '2222455189',
    idiomas: ['Español'],
    anios: 21,
    universidad: 'Universidad Popular Autónoma del Estado de Puebla',
    universidad_especialidad: 'Instituto Nacional de Cardiología Ignacio Chávez',
    consejo: 'Consejo Mexicano de Cardiología',
    vigencia: '2027',
    aseguradoras: ['GNP', 'Seguros Monterrey', 'Banorte'],
    rating: 4.9,
    resenas: 212,
    verificado: '2026-01-28',
    fundador: true,
    consultorio: {
      calle: 'Avenida 25 Poniente',
      numero: '1316',
      torre: '',
      piso: '2',
      consultorio: '204',
      colonia: 'La Paz',
      cp: '72160',
      ciudad: 'puebla',
      lat: 19.0455,
      lng: -98.222,
      referencias: 'A media cuadra del Paseo Bravo, edificio de fachada blanca junto a la farmacia.',
      estacionamiento: 'Estacionamiento público a 50 metros, sobre la misma calle.',
      horario: 'Lunes a viernes de 9:00 a 14:00 y de 16:00 a 20:00.',
      finSemana: false,
    },
    servicios: [
      ['Consulta de cardiología', 1100, true],
      ['Electrocardiograma', 450, true],
      ['Ecocardiograma', 2200, true],
      ['Prueba de esfuerzo', 2600, true],
    ],
    faqs: [
      ['¿Debo ir en ayunas?', 'Para la consulta no es necesario. Si te vamos a hacer prueba de esfuerzo, sí conviene: te lo indicamos al confirmar.'],
      ['¿Puedo llevar estudios de otro médico?', 'Sí, y ayuda mucho. Lleva electrocardiogramas, análisis de laboratorio y la lista de medicamentos que tomas.'],
    ],
  },
  {
    nombre: 'Alejandra',
    apellidos: 'Bonilla Herrera',
    titulo: 'Dra.',
    genero: 'femenino',
    cedula: '6743019',
    cedula_especialidad: '10112287',
    especialidades: ['esp-pediatria'],
    bio: 'Pediatra con consulta en San Manuel. Atiende control del niño sano, vacunación y padecimientos comunes de la infancia. Da seguimiento de crecimiento con gráficas desde el nacimiento.',
    telefono: '2222981340',
    whatsapp: '2222981340',
    idiomas: ['Español', 'Inglés'],
    anios: 9,
    universidad: 'Benemérita Universidad Autónoma de Puebla',
    universidad_especialidad: 'Hospital Infantil de México Federico Gómez',
    consejo: 'Consejo Mexicano de Certificación en Pediatría',
    vigencia: '2029',
    aseguradoras: ['AXA', 'Metlife'],
    rating: 4.7,
    resenas: 86,
    verificado: '2026-02-03',
    fundador: true,
    consultorio: {
      calle: 'Calle 4 Sur',
      numero: '4508',
      torre: '',
      piso: '1',
      consultorio: '103',
      colonia: 'San Manuel',
      cp: '72570',
      ciudad: 'puebla',
      lat: 19.002,
      lng: -98.203,
      referencias: 'Enfrente del parque de San Manuel, en la planta alta de la clínica de fachada de ladrillo.',
      estacionamiento: 'Cajones propios en el patio interior, cuatro lugares.',
      horario: 'Lunes a viernes de 15:00 a 20:00. Sábados de 9:00 a 13:00.',
      finSemana: true,
    },
    servicios: [
      ['Consulta pediátrica', 700, true],
      ['Control del niño sano', 700, true],
      ['Aplicación de vacunas', null, false],
    ],
    faqs: [
      ['¿Aplica vacunas del esquema nacional?', 'Sí, y también las que no entran en el esquema gratuito. El costo depende de la vacuna; te lo confirmo por WhatsApp antes de tu visita.'],
      ['¿Atiende recién nacidos?', 'Sí, desde el alta del hospital. La primera consulta del recién nacido conviene tenerla dentro de la primera semana.'],
    ],
  },
  {
    nombre: 'Gustavo',
    apellidos: 'Meneses Carrasco',
    titulo: 'Dr.',
    genero: 'masculino',
    cedula: '7120458',
    cedula_especialidad: '10556731',
    especialidades: ['esp-odontologia'],
    bio: 'Cirujano dentista con práctica general y ortodoncia. Trabaja limpieza, resinas, endodoncia y brackets metálicos y estéticos. El plan de tratamiento se entrega por escrito con costos desglosados antes de empezar.',
    telefono: '2223770926',
    whatsapp: '2223770926',
    idiomas: ['Español'],
    anios: 15,
    universidad: 'Universidad de las Américas Puebla',
    universidad_especialidad: 'Universidad Autónoma de Nuevo León',
    consejo: '',
    vigencia: '',
    aseguradoras: ['Dentegra'],
    rating: 4.6,
    resenas: 154,
    verificado: '2026-02-19',
    fundador: true,
    consultorio: {
      calle: 'Calzada Zavaleta',
      numero: '1108',
      torre: 'Plaza Zavaleta',
      piso: 'PB',
      consultorio: 'L-12',
      colonia: 'Zavaleta',
      cp: '72170',
      ciudad: 'puebla',
      lat: 19.047,
      lng: -98.254,
      referencias: 'En la plaza comercial de la esquina con Camino Real a Cholula, local con cristal esmerilado.',
      estacionamiento: 'Estacionamiento de la plaza, sin costo las dos primeras horas.',
      horario: 'Lunes a viernes de 10:00 a 19:00. Sábados de 10:00 a 15:00.',
      finSemana: true,
    },
    servicios: [
      ['Consulta y diagnóstico', 400, true],
      ['Limpieza dental', 850, true],
      ['Resina', 950, true],
      ['Endodoncia', 3200, true],
      ['Ortodoncia, primer pago', 6500, true],
    ],
    faqs: [
      ['¿Cuánto cuesta un tratamiento de ortodoncia completo?', 'Depende del caso. En la consulta de valoración se entrega el plan por escrito con el total y las mensualidades, sin costos que aparezcan después.'],
      ['¿Atiende urgencias por dolor?', 'Sí. Escríbeme por WhatsApp describiendo lo que pasa y busco espacio el mismo día.'],
    ],
  },
  {
    nombre: 'Paulina',
    apellidos: 'Rentería Escobar',
    titulo: 'Lic.',
    genero: 'femenino',
    cedula: '9034761',
    cedula_especialidad: '',
    especialidades: ['esp-psicologia'],
    bio: 'Psicóloga clínica con enfoque cognitivo-conductual. Terapia individual para adultos y jóvenes, y terapia de pareja. Sesiones presenciales en La Noria.',
    telefono: '2224418052',
    whatsapp: '2224418052',
    idiomas: ['Español'],
    anios: 8,
    universidad: 'Universidad Iberoamericana Puebla',
    universidad_especialidad: '',
    consejo: '',
    vigencia: '',
    aseguradoras: [],
    rating: 5,
    resenas: 41,
    verificado: '2026-02-24',
    fundador: true,
    consultorio: {
      calle: 'Avenida Nacional',
      numero: '212',
      torre: '',
      piso: '3',
      consultorio: '301',
      colonia: 'La Noria',
      cp: '72410',
      ciudad: 'puebla',
      lat: 19.027,
      lng: -98.213,
      referencias: 'Edificio de consultorios sobre la avenida, entrada discreta al lado de la cafetería.',
      estacionamiento: 'Estacionamiento en la calle, generalmente hay lugar.',
      horario: 'Lunes a jueves de 11:00 a 20:00. Viernes de 11:00 a 15:00.',
      finSemana: false,
    },
    servicios: [
      ['Sesión individual', 650, true],
      ['Terapia de pareja', 900, true],
    ],
    faqs: [
      ['¿Cada cuándo son las sesiones?', 'Al principio suelen ser semanales. Conforme avanza el proceso se espacian; eso se decide contigo, no de entrada.'],
      ['¿La psicóloga receta medicamento?', 'No. La prescripción de medicamento corresponde a psiquiatría; si tu caso lo requiere, se te canaliza.'],
    ],
  },
  {
    nombre: 'Diego',
    apellidos: 'Ávalos Montiel',
    titulo: 'L.N.',
    genero: 'masculino',
    cedula: '8871245',
    cedula_especialidad: '',
    especialidades: ['esp-nutricion'],
    bio: 'Nutriólogo clínico. Planes de alimentación para control de peso, diabetes y rendimiento deportivo, con medición de composición corporal por bioimpedancia en cada revisión.',
    telefono: '2221936740',
    whatsapp: '2221936740',
    idiomas: ['Español', 'Inglés'],
    anios: 6,
    universidad: 'Universidad Popular Autónoma del Estado de Puebla',
    universidad_especialidad: '',
    consejo: '',
    vigencia: '',
    aseguradoras: [],
    rating: 4.8,
    resenas: 63,
    verificado: '2026-03-02',
    fundador: true,
    consultorio: {
      calle: 'Vía Atlixcáyotl',
      numero: '2499',
      torre: 'Torre Ejecutiva',
      piso: '8',
      consultorio: '804',
      colonia: 'Angelópolis',
      cp: '72197',
      ciudad: 'puebla',
      lat: 19.0158,
      lng: -98.2432,
      referencias: 'Torre de oficinas con recepción; hay que registrarse con identificación en la entrada.',
      estacionamiento: 'Estacionamiento del edificio con pensión por hora.',
      horario: 'Lunes a viernes de 8:00 a 14:00 y de 16:00 a 20:00.',
      finSemana: false,
    },
    servicios: [
      ['Primera consulta con plan de alimentación', 800, true],
      ['Consulta de seguimiento', 500, true],
      ['Medición de composición corporal', 350, true],
    ],
    faqs: [
      ['¿Tengo que llevar estudios de laboratorio?', 'Si los tienes recientes, llévalos. Si no, en la primera consulta te indico cuáles conviene hacer.'],
      ['¿Los planes incluyen suplementos?', 'Solo si hacen falta y se justifica. No se venden suplementos en el consultorio.'],
    ],
  },
  {
    nombre: 'Verónica',
    apellidos: 'Landa Quintero',
    titulo: 'Dra.',
    genero: 'femenino',
    cedula: '6218903',
    cedula_especialidad: '9784110',
    especialidades: ['esp-ginecologia'],
    bio: 'Ginecóloga y obstetra en el centro de San Andrés Cholula. Control prenatal, atención de parto y cesárea, colposcopía y planificación familiar.',
    telefono: '2226730418',
    whatsapp: '2226730418',
    idiomas: ['Español'],
    anios: 17,
    universidad: 'Benemérita Universidad Autónoma de Puebla',
    universidad_especialidad: 'Hospital General de México Eduardo Liceaga',
    consejo: 'Consejo Mexicano de Ginecología y Obstetricia',
    vigencia: '2027',
    aseguradoras: ['GNP', 'AXA'],
    rating: 4.9,
    resenas: 178,
    verificado: '2026-01-15',
    fundador: true,
    consultorio: {
      calle: 'Calle 4 Oriente',
      numero: '15',
      torre: '',
      piso: 'PB',
      consultorio: 'A',
      colonia: 'San Andrés Cholula centro',
      cp: '72810',
      ciudad: 'cholula',
      lat: 19.0533,
      lng: -98.301,
      referencias: 'A una cuadra del zócalo de San Andrés, casa de fachada colonial con portón verde.',
      estacionamiento: 'Sin estacionamiento propio; hay pensión a dos cuadras.',
      horario: 'Lunes, miércoles y viernes de 10:00 a 18:00. Martes y jueves de 16:00 a 20:00.',
      finSemana: false,
    },
    servicios: [
      ['Consulta ginecológica', 900, true],
      ['Control prenatal', 900, true],
      ['Papanicolaou y colposcopía', 1400, true],
      ['Ultrasonido obstétrico', 1100, true],
    ],
    faqs: [
      ['¿Atiende partos?', 'Sí, en hospital. En la consulta se revisa el plan de parto y el hospital donde se atendería.'],
      ['¿Puedo ir acompañada?', 'Siempre. Puedes entrar al consultorio con quien tú decidas.'],
    ],
  },
  {
    nombre: 'Emilio',
    apellidos: 'Cuéllar Bautista',
    titulo: 'Dr.',
    genero: 'masculino',
    cedula: '7503362',
    cedula_especialidad: '10287905',
    especialidades: ['esp-ortopedia'],
    bio: 'Ortopedista y traumatólogo con enfoque en rodilla y hombro. Atiende lesiones deportivas, desgaste articular y rehabilitación posquirúrgica, en coordinación con fisioterapia.',
    telefono: '2225580174',
    whatsapp: '2225580174',
    idiomas: ['Español', 'Inglés'],
    anios: 13,
    universidad: 'Universidad Anáhuac Puebla',
    universidad_especialidad: 'Instituto Nacional de Rehabilitación',
    consejo: 'Consejo Mexicano de Ortopedia y Traumatología',
    vigencia: '2028',
    aseguradoras: ['GNP', 'Seguros Monterrey', 'Metlife'],
    rating: 4.7,
    resenas: 95,
    verificado: '2026-02-06',
    fundador: true,
    consultorio: {
      calle: 'Avenida Juárez',
      numero: '308',
      torre: 'Torre Cholula',
      piso: '4',
      consultorio: '402',
      colonia: 'San Andrés Cholula centro',
      cp: '72810',
      ciudad: 'cholula',
      lat: 19.0547,
      lng: -98.2988,
      referencias: 'Edificio de consultorios frente al mercado; el elevador está al fondo del pasillo.',
      estacionamiento: 'Estacionamiento propio en el sótano.',
      horario: 'Lunes a viernes de 9:00 a 15:00.',
      finSemana: false,
    },
    servicios: [
      ['Consulta de ortopedia', 1000, true],
      ['Infiltración articular', 2500, true],
      ['Valoración de lesión deportiva', 1000, true],
    ],
    faqs: [
      ['¿Necesito una resonancia antes de la consulta?', 'No necesariamente. En la consulta se define qué estudio hace falta, si es que hace falta alguno.'],
      ['¿Da seguimiento con fisioterapia?', 'Sí. El plan de rehabilitación se coordina con el fisioterapeuta y se revisa en cada cita.'],
    ],
  },
  {
    nombre: 'Sofía',
    apellidos: 'Nieto Ramírez',
    titulo: 'Dra.',
    genero: 'femenino',
    cedula: '8146927',
    cedula_especialidad: '',
    especialidades: ['esp-medicina-general'],
    bio: 'Médica general en el centro de Atlixco. Consulta de primer contacto, control de diabetes e hipertensión, certificados médicos y curaciones.',
    telefono: '2444723815',
    whatsapp: '2444723815',
    idiomas: ['Español'],
    anios: 7,
    universidad: 'Benemérita Universidad Autónoma de Puebla',
    universidad_especialidad: '',
    consejo: '',
    vigencia: '',
    aseguradoras: [],
    rating: 4.5,
    resenas: 52,
    verificado: '2026-03-05',
    fundador: true,
    consultorio: {
      calle: 'Avenida Hidalgo',
      numero: '410',
      torre: '',
      piso: 'PB',
      consultorio: '2',
      colonia: 'Atlixco centro',
      cp: '74200',
      ciudad: 'atlixco',
      lat: 18.908,
      lng: -98.436,
      referencias: 'Media cuadra antes del zócalo, junto a la papelería.',
      estacionamiento: 'Estacionamiento en la calle.',
      horario: 'Lunes a sábado de 9:00 a 14:00 y de 16:00 a 19:00.',
      finSemana: true,
    },
    servicios: [
      ['Consulta general', 400, true],
      ['Certificado médico', 350, true],
      ['Curación y retiro de puntos', 300, true],
    ],
    faqs: [
      ['¿Atiende sin cita?', 'Sí, por orden de llegada. Si escribes por WhatsApp te digo cómo está la sala en ese momento.'],
      ['¿Hace visitas a domicilio?', 'En casos justificados dentro de Atlixco centro. Se acuerda por WhatsApp.'],
    ],
  },
  {
    nombre: 'Hugo',
    apellidos: 'Pastrana Lezama',
    titulo: 'Dr.',
    genero: 'masculino',
    cedula: '7659384',
    cedula_especialidad: '',
    especialidades: ['esp-odontologia'],
    bio: 'Cirujano dentista en Atlixco. Odontología general para toda la familia, prótesis fijas y removibles, y blanqueamiento.',
    telefono: '2444390267',
    whatsapp: '2444390267',
    idiomas: ['Español'],
    anios: 11,
    universidad: 'Benemérita Universidad Autónoma de Puebla',
    universidad_especialidad: '',
    consejo: '',
    vigencia: '',
    aseguradoras: [],
    rating: null,
    resenas: null,
    verificado: '2026-03-09',
    fundador: true,
    consultorio: {
      calle: 'Calle 5 Poniente',
      numero: '107',
      torre: '',
      piso: 'PB',
      consultorio: '',
      colonia: 'Atlixco centro',
      cp: '74200',
      ciudad: 'atlixco',
      lat: 18.9095,
      lng: -98.4381,
      referencias: 'Casa blanca con letrero de consultorio dental, a espaldas del mercado.',
      estacionamiento: 'Cochera para dos autos.',
      horario: 'Lunes a viernes de 10:00 a 14:00 y de 16:00 a 20:00. Sábados de 10:00 a 14:00.',
      finSemana: true,
    },
    servicios: [
      ['Consulta y valoración', 300, true],
      ['Limpieza dental', 700, true],
      ['Extracción simple', 800, true],
      ['Blanqueamiento', 2800, true],
    ],
    faqs: [
      ['¿Atiende niños?', 'Sí, desde los cuatro años para limpieza y revisión.'],
      ['¿Aceptan pago con tarjeta?', 'Sí, tarjeta de débito y crédito, y transferencia.'],
    ],
  },
  {
    nombre: 'Ana Karen',
    apellidos: 'Vidal Rojas',
    titulo: 'Lic.',
    genero: 'femenino',
    cedula: '9271408',
    cedula_especialidad: '',
    especialidades: ['esp-psicologia'],
    bio: 'Psicóloga infantil y de adolescentes. Trabaja problemas de conducta, ansiedad escolar y acompañamiento a padres, con juego terapéutico para los más pequeños.',
    telefono: '2223846159',
    whatsapp: '2223846159',
    idiomas: ['Español'],
    anios: 10,
    universidad: 'Universidad Iberoamericana Puebla',
    universidad_especialidad: 'Universidad de las Américas Puebla',
    consejo: '',
    vigencia: '',
    aseguradoras: [],
    rating: 4.9,
    resenas: 74,
    verificado: '2026-02-27',
    fundador: true,
    consultorio: {
      calle: 'Camino Real a Cholula',
      numero: '4128',
      torre: '',
      piso: '2',
      consultorio: '21',
      colonia: 'Zavaleta',
      cp: '72150',
      ciudad: 'puebla',
      lat: 19.0494,
      lng: -98.2512,
      referencias: 'Plaza pequeña con fachada de madera; el consultorio está en la parte de arriba, subiendo por la escalera exterior.',
      estacionamiento: 'Cajones de la plaza, sin costo.',
      horario: 'Lunes a viernes de 14:00 a 20:00. Sábados de 9:00 a 14:00.',
      finSemana: true,
    },
    servicios: [
      ['Sesión infantil', 700, true],
      ['Sesión para adolescentes', 700, true],
      ['Orientación a padres', 800, true],
    ],
    faqs: [
      ['¿Los papás entran a la sesión?', 'La primera entrevista es con los papás. Después las sesiones son con el niño o la niña, y cada cierto tiempo hay una de devolución con ustedes.'],
      ['¿Hacen evaluaciones psicométricas?', 'Sí, cuando la escuela las solicita o el caso lo amerita. Se cotizan aparte.'],
    ],
  },
  {
    nombre: 'Fernando',
    apellidos: 'Osorio Galindo',
    titulo: 'Dr.',
    genero: 'masculino',
    cedula: '6584127',
    cedula_especialidad: '9903458',
    especialidades: ['esp-oftalmologia'],
    bio: 'Oftalmólogo con consulta en La Paz. Graduación de lentes, revisión de retina, glaucoma y cirugía de catarata con lente intraocular.',
    telefono: '2222167093',
    whatsapp: '2222167093',
    idiomas: ['Español', 'Inglés'],
    anios: 19,
    universidad: 'Universidad Nacional Autónoma de México',
    universidad_especialidad: 'Asociación para Evitar la Ceguera en México',
    consejo: 'Consejo Mexicano de Oftalmología',
    vigencia: '2026',
    aseguradoras: ['AXA', 'Banorte'],
    rating: 4.6,
    resenas: 110,
    verificado: '2026-02-14',
    fundador: true,
    consultorio: {
      calle: 'Avenida 31 Poniente',
      numero: '905',
      torre: 'Torre Médica La Paz',
      piso: '6',
      consultorio: '603',
      colonia: 'La Paz',
      cp: '72160',
      ciudad: 'puebla',
      lat: 19.0432,
      lng: -98.2265,
      referencias: 'Torre médica de cristal sobre la 31 Poniente; recepción de oftalmología en el sexto piso.',
      estacionamiento: 'Estacionamiento de la torre, con validación en el consultorio.',
      horario: 'Lunes a viernes de 9:00 a 14:00 y de 16:00 a 19:00.',
      finSemana: false,
    },
    servicios: [
      ['Consulta oftalmológica', 950, true],
      ['Estudio de campos visuales', 1300, true],
      ['Cirugía de catarata', null, false],
    ],
    faqs: [
      ['¿Puedo manejar después de la consulta?', 'Si te dilatamos la pupila, no conviene manejar en las siguientes horas. Ven acompañado o considera un taxi de regreso.'],
      ['¿Recetan lentes ahí mismo?', 'La graduación se entrega en el consultorio. La óptica donde los mandas hacer la eliges tú.'],
    ],
  },
];

/** Arma las diez tablas a partir de las semillas de arriba. */
export function construirSemilla(): BaseListaMedica {
  const profesionales: Profesional[] = [];
  const prof_especialidad: ProfEspecialidad[] = [];
  const consultorios: Consultorio[] = [];
  const servicios: Servicio[] = [];
  const faqs: Faq[] = [];

  SEMILLAS.forEach((s, i) => {
    const id = `demo-${String(i + 1).padStart(2, '0')}`;
    const principal = ESPECIALIDADES_BASE.find((e) => e.id === s.especialidades[0]);
    const slug = slugify(
      `${s.nombre} ${s.apellidos} ${principal?.nombre ?? ''} ${s.consultorio.ciudad}`,
    );

    profesionales.push({
      id,
      nombre: s.nombre,
      apellidos: s.apellidos,
      titulo: s.titulo,
      cedula: s.cedula,
      cedula_especialidad: s.cedula_especialidad,
      slug,
      bio: s.bio,
      foto_url: '',
      telefono: s.telefono,
      whatsapp: s.whatsapp,
      genero: s.genero,
      idiomas: s.idiomas,
      anios_experiencia: s.anios,
      universidad: s.universidad,
      universidad_especialidad: s.universidad_especialidad,
      certificacion_consejo: s.consejo,
      vigencia_certificacion: s.vigencia,
      aseguradoras: s.aseguradoras,
      google_place_id: '',
      google_rating: s.rating,
      google_reviews_count: s.resenas,
      google_sync_at: s.rating === null ? null : '2026-03-10T12:00:00.000Z',
      verificado_en: s.verificado,
      evidencia_verificacion_url: '',
      estatus: 'demo',
      completitud_pct: 0,
      es_fundador: s.fundador,
      fecha_alta: '2026-03-10T12:00:00.000Z',
      orden: i + 1,
    });

    s.especialidades.forEach((especialidad_id, j) => {
      prof_especialidad.push({ profesional_id: id, especialidad_id, es_principal: j === 0 });
    });

    const c = s.consultorio;
    consultorios.push({
      id: `${id}-cons`,
      profesional_id: id,
      calle: c.calle,
      numero: c.numero,
      torre: c.torre,
      piso: c.piso,
      consultorio: c.consultorio,
      colonia: c.colonia,
      cp: c.cp,
      ciudad: c.ciudad,
      lat: c.lat,
      lng: c.lng,
      referencias: c.referencias,
      estacionamiento: c.estacionamiento,
      horario_texto: c.horario,
      atiende_fin_semana: c.finSemana,
    });

    s.servicios.forEach(([nombre, precio, publicar], j) => {
      servicios.push({
        id: `${id}-serv-${j + 1}`,
        profesional_id: id,
        nombre,
        precio_desde: precio,
        publicar_precio: publicar,
      });
    });

    s.faqs.forEach(([pregunta, respuesta], j) => {
      faqs.push({ id: `${id}-faq-${j + 1}`, profesional_id: id, pregunta, respuesta, orden: j + 1 });
    });
  });

  return {
    profesionales,
    especialidades: ESPECIALIDADES_BASE,
    prof_especialidad,
    consultorios,
    servicios,
    faqs,
    clics: [],
    busquedas: [],
    verificaciones: [],
    resenas: [],
  };
}
